name: Upload Release Build

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: macos-11
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '13.0'
      - uses: actions/checkout@v2
      - name: Build
        run: swift package update; swift build -c release
      - name: Zip
        run: zip --junk-paths runeterrawallpaper.zip .build/release/runeterrawallpaper
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }} 
          asset_path: ./runeterrawallpaper.zip
          asset_name: runeterrawallpaper.zip
          asset_content_type: application/zip
